"""Synthetic event catalogs. No real hosts, files, or networks are touched."""
from __future__ import annotations

from typing import Any

SCENARIOS: dict[str, dict[str, Any]] = {
    "SCN-001": {
        "name": "Lab workstation ransomware preparation",
        "kind": "attack",
        "description": "LAB-PC-21 student path toward file and backup servers.",
        "events": [
            {
                "id": "EVT-001",
                "timestamp": "10:01",
                "event_type": "suspicious_process",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1059",
                "summary": "Unusual PowerShell spawned from office document context on LAB-PC-21.",
                "details": {"process": "powershell.exe", "parent": "winword.exe", "cmd_len": 180},
            },
            {
                "id": "EVT-002",
                "timestamp": "10:02",
                "event_type": "mass_file_modification",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1486",
                "summary": "Burst of file write operations across student documents folder.",
                "details": {"files_touched": 184, "window_sec": 12},
            },
            {
                "id": "EVT-003",
                "timestamp": "10:02",
                "event_type": "rapid_file_rename",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1486",
                "summary": "Rapid rename sequence consistent with staging, not a single approved app.",
                "details": {"renames": 96, "window_sec": 9},
            },
            {
                "id": "EVT-004",
                "timestamp": "10:03",
                "event_type": "credential_access",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1078",
                "summary": "LSASS-adjacent credential access pattern for student.kumar.",
                "details": {"credential_id": "CRED-STU-21"},
            },
            {
                "id": "EVT-005",
                "timestamp": "10:04",
                "event_type": "privilege_escalation",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1068",
                "summary": "Local privilege elevation enabling further movement.",
                "details": {"from": "Standard", "to": "Elevated"},
            },
            {
                "id": "EVT-006",
                "timestamp": "10:05",
                "event_type": "lateral_movement",
                "asset_id": "FAC-PC-07",
                "user": "student.kumar",
                "mitre": "T1021",
                "summary": "Remote service authentication from LAB-PC-21 toward FAC-PC-07.",
                "details": {"source": "LAB-PC-21", "destination": "FAC-PC-07"},
            },
            {
                "id": "EVT-007",
                "timestamp": "10:06",
                "event_type": "file_server_access",
                "asset_id": "FILE-SRV-01",
                "user": "faculty.meena",
                "mitre": "T1021",
                "summary": "File share access to FILE-SRV-01 using faculty path.",
                "details": {"share": "\\\\FILE-SRV-01\\campus"},
            },
            {
                "id": "EVT-008",
                "timestamp": "10:07",
                "event_type": "backup_access_attempt",
                "asset_id": "BACKUP-SRV-01",
                "user": "svc.backup",
                "mitre": "T1486",
                "summary": "Attempted backup catalog access indicating recovery disruption.",
                "details": {"target": "BACKUP-SRV-01"},
            },
        ],
    },
    "SCN-002": {
        "name": "Early detection / low impact",
        "kind": "attack",
        "description": "Early suspicious process and limited file activity without ransomware-likely correlation.",
        "events": [
            {
                "id": "E2-001",
                "timestamp": "10:01",
                "event_type": "suspicious_process",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1059",
                "summary": "Unusual PowerShell spawned from office document context on LAB-PC-21.",
                "details": {"process": "powershell.exe", "parent": "winword.exe", "cmd_len": 180},
            },
            {
                "id": "E2-002",
                "timestamp": "10:02",
                "event_type": "mass_file_modification",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1486",
                "summary": "Limited student-document writes without credential or lateral correlation.",
                "details": {"files_touched": 40, "window_sec": 20},
            },
        ],
    },
    "SCN-003": {
        "name": "Credential-first attack",
        "kind": "attack",
        "description": "Credential access and privilege escalation on the lab workstation.",
        "events": [
            {
                "id": "E3-001",
                "timestamp": "10:01",
                "event_type": "suspicious_process",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1059",
                "summary": "Initial suspicious process on LAB-PC-21.",
                "details": {"process": "powershell.exe"},
            },
            {
                "id": "E3-002",
                "timestamp": "10:03",
                "event_type": "credential_access",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1078",
                "summary": "LSASS-adjacent credential access pattern for student.kumar.",
                "details": {"credential_id": "CRED-STU-21"},
            },
            {
                "id": "E3-003",
                "timestamp": "10:04",
                "event_type": "privilege_escalation",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1068",
                "summary": "Local privilege elevation enabling further movement.",
                "details": {"from": "Standard", "to": "Elevated"},
            },
        ],
    },
    "SCN-004": {
        "name": "Lateral movement attack",
        "kind": "attack",
        "description": "Observed path through privilege escalation into FAC-PC-07.",
        "events": [
            {
                "id": "E4-001",
                "timestamp": "10:01",
                "event_type": "suspicious_process",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1059",
                "summary": "Suspicious process on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E4-002",
                "timestamp": "10:03",
                "event_type": "credential_access",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1078",
                "summary": "Credential access on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E4-003",
                "timestamp": "10:04",
                "event_type": "privilege_escalation",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1068",
                "summary": "Privilege escalation on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E4-004",
                "timestamp": "10:05",
                "event_type": "lateral_movement",
                "asset_id": "FAC-PC-07",
                "user": "student.kumar",
                "mitre": "T1021",
                "summary": "Remote service authentication from LAB-PC-21 toward FAC-PC-07.",
                "details": {"source": "LAB-PC-21", "destination": "FAC-PC-07"},
            },
        ],
    },
    "SCN-005": {
        "name": "High adaptation / alternate path",
        "kind": "attack",
        "description": "Progression to predicted file-server protection where simulated adaptation can pivot.",
        "events": [
            {
                "id": "E5-001",
                "timestamp": "10:01",
                "event_type": "suspicious_process",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1059",
                "summary": "Suspicious process on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E5-002",
                "timestamp": "10:02",
                "event_type": "mass_file_modification",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1486",
                "summary": "Mass file modification on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E5-003",
                "timestamp": "10:02",
                "event_type": "rapid_file_rename",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1486",
                "summary": "Rapid file renaming on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E5-004",
                "timestamp": "10:03",
                "event_type": "credential_access",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1078",
                "summary": "Credential access on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E5-005",
                "timestamp": "10:04",
                "event_type": "privilege_escalation",
                "asset_id": "LAB-PC-21",
                "user": "student.kumar",
                "mitre": "T1068",
                "summary": "Privilege escalation on LAB-PC-21.",
                "details": {},
            },
            {
                "id": "E5-006",
                "timestamp": "10:05",
                "event_type": "lateral_movement",
                "asset_id": "FAC-PC-07",
                "user": "student.kumar",
                "mitre": "T1021",
                "summary": "Lateral movement to FAC-PC-07.",
                "details": {},
            },
        ],
    },
    "SCN-006": {
        "name": "Benign suspicious activity / false-positive scenario",
        "kind": "benign",
        "description": "Approved admin PowerShell without impact correlation.",
        "events": [
            {
                "id": "E6-001",
                "timestamp": "11:01",
                "event_type": "suspicious_process",
                "asset_id": "ADMIN-PC-03",
                "user": "admin.ravi",
                "mitre": "T1059",
                "summary": "PowerShell used by administrator for inventory script.",
                "details": {"process": "powershell.exe", "signed": True, "approved": True},
            }
        ],
    },
    "SCN-FP-001": {
        "name": "Normal PowerShell",
        "kind": "benign",
        "description": "Approved admin script on ADMIN-PC-03 without impact correlation.",
        "events": [
            {
                "id": "FP-001",
                "timestamp": "11:01",
                "event_type": "suspicious_process",
                "asset_id": "ADMIN-PC-03",
                "user": "admin.ravi",
                "mitre": "T1059",
                "summary": "PowerShell used by administrator for inventory script.",
                "details": {"process": "powershell.exe", "signed": True, "approved": True},
            }
        ],
    },
    "SCN-FP-002": {
        "name": "Large legitimate file copy",
        "kind": "benign",
        "description": "Faculty copying lecture materials.",
        "events": [
            {
                "id": "FP-002",
                "timestamp": "11:10",
                "event_type": "mass_file_modification",
                "asset_id": "FAC-PC-07",
                "user": "faculty.meena",
                "mitre": "T1486",
                "summary": "Bulk copy of lecture PDFs to course folder.",
                "details": {"files_touched": 210, "approved_app": "explorer.exe"},
            }
        ],
    },
    "SCN-FP-003": {
        "name": "Backup operation",
        "kind": "benign",
        "description": "Scheduled backup job using service account.",
        "events": [
            {
                "id": "FP-003",
                "timestamp": "02:00",
                "event_type": "backup_access_attempt",
                "asset_id": "BACKUP-SRV-01",
                "user": "svc.backup",
                "mitre": "T1486",
                "summary": "Nightly backup catalog sync.",
                "details": {"job": "nightly-full", "approved": True},
            }
        ],
    },
    "SCN-FP-004": {
        "name": "Software update",
        "kind": "benign",
        "description": "Endpoint update service writing many files.",
        "events": [
            {
                "id": "FP-004",
                "timestamp": "03:15",
                "event_type": "mass_file_modification",
                "asset_id": "LAB-PC-22",
                "user": "system",
                "mitre": "T1486",
                "summary": "Windows update staging files.",
                "details": {"approved_app": "wuauclt.exe"},
            }
        ],
    },
    "SCN-FP-005": {
        "name": "Bulk rename by approved application",
        "kind": "benign",
        "description": "Media class batch rename tool.",
        "events": [
            {
                "id": "FP-005",
                "timestamp": "14:22",
                "event_type": "rapid_file_rename",
                "asset_id": "LAB-PC-22",
                "user": "student.priya",
                "mitre": "T1486",
                "summary": "Course-approved bulk rename utility.",
                "details": {"approved_app": "BulkRenameUtility.exe", "renames": 80},
            }
        ],
    },
}


def scenario_catalog() -> list[dict[str, Any]]:
    return [
        {"id": sid, "name": meta["name"], "kind": meta["kind"], "description": meta["description"]}
        for sid, meta in SCENARIOS.items()
    ]
